title: Baseball Stats Tracker
description: Advanced performance tracking for baseball athletes.
baseurl: ""
url: "https://sentientsourdough.github.io"

# Build settings
markdown: kramdown

# List files/folders to ignore during the build process
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - node_modules
  - vendor
  - TODO.txt
